name: dqoi_example
description: Example application for the 'dqoi' application library

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dqoi:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
