name: dqoi
description: A Dart implementation of the "Quite OK Image Format", with a command line interface for console use and a library for use in applications.
version: 0.0.0-alpha.1
repository: https://github.com/JaffaKetchup/dqoi
issue_tracker: https://github.com/JaffaKetchup/dqoi/issues

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  path: ^1.8.1
  args: ^2.3.0
  image: ^3.1.3

dev_dependencies:
  lints: ^1.0.0

executables:
  dqoi:
