name: dqoi
description: A Dart implementation of the "Quite OK Image Format", with a command line interface for console use and a library for use in applications.
version: 1.2.0
repository: https://github.com/JaffaKetchup/dqoi
issue_tracker: https://github.com/JaffaKetchup/dqoi/issues

funding:
  - https://github.com/sponsors/JaffaKetchup
  - https://ko-fi.com/jaffaketchup

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  args: ^2.3.0
  flutter:
    sdk: flutter
  image: ^3.2.0
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0

executables:
  dqoi:
